apiVersion: v1
kind: Service
metadata:
  labels:
    name: marksolters-v1
  name: marksolters-v1
spec:
  type: NodePort
  selector:
    role: marksolters-v1
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: app
  - name: nginx-http
    port: 8080
    protocol: TCP
    targetPort: http
    nodePort: 31757
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
