apiVersion: v1
kind: Service
metadata:
  labels:
    name: marksolters-v1
  name: marksolters-v1
spec:
  type: LoadBalancer
  selector:
    role: marksolters-v1
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
